### ISSUE TITLE
Improve testing on tiles

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#288]
All tiles must test against private content:

* drag&drop a private object to the tile
* logged in user should be able to see the content
* visit the page as an anonymous user
* tile must be empty

probably we need to display some sort of message for the logged in user.

**Comment by idgserpro** [comment]
Why was this issue closed? Not enough hands?

Should the responsibility of deciding what should be done for private content a collective.cover's behavior that can at least be inherited for individual tiles third-party implementations, or should we leave it entirely for a tiles implementation?

We have a client relating a bug in a news tile, since the news is in private state and still being shown in a cover (we thought that upgrading the collective.nitf to last version (2.0b4) would fix it but we're having the same erratic behavior). Since you're more familiar with collective.cover source code and it's internals, where should this be fixed?

**Comment by hvelarde** [comment]
I prefer to have specific issues and use cases; if the issues you're talking about is in the NITF tile, then it has to be opened there; provide the steps to reproduce and a test demonstrating the issue, if you can.

**Comment by idgserpro** [comment]
Done! https://github.com/collective/collective.nitf/issues/185
