### ISSUE TITLE
Content of Embedding Tile is not security checked

### ISSUE THREAD

**Issue by tomgross** [collective/collective.cover#297]
It is possible to add arbitrary HTML / JavaScript code into the Embedding Tile. 

```
<script type="text/javascript">
<!--
alert("Something evil!");
//-->
</script>
````

The safe filter of Plone should be applied to some extent.

**Comment by tomgross** [comment]
How about using noembed like in plone.app.mosaic to generate tile?

**Comment by hvelarde** [comment]
because Noembed works only with sites and the embed tile can be used to embed anything; just an example: before the refresh behavior was implemented we used the embed tile to refresh the front page of a site by inserting some JS code.

in the future we will be able to use Plone's standard tiles so we will be able to use the tile used in Mosaic.
