### ISSUE TITLE
Fields in registry.xml without purge="false"

### ISSUE THREAD

**Issue by idgserpro** [collective/collective.cover#465]
Fields styles and layouts in registry.xml (https://github.com/collective/collective.cover/blob/master/src/collective/cover/profiles/default/registry.xml#L21) no have purge = "false". This is bad because every time the collective.cover is reinstalled, the values of these records will be overwritten, even if they have been modified by other products or by others.

Even without reinstalling collective.cover directly it can be reinstalled when it is prerequisite of another product in metadata.xml. For example:

https://github.com/plonegovbr/brasil.gov.agenda/blob/master/src/brasil/gov/agenda/profiles/default/metadata.xml#L5

See also: https://github.com/plonegovbr/brasil.gov.portal/issues/154#issuecomment-64394367

**Comment by fredvd** [comment]
This is a more generic problem in Plone/Generic Setup. Adding purge="false" to the generic setup importer will only give a partial solution because the default c.cover styles will still be added again. 

What you can do is store the correct styles in a registry.xml in a policy add'on for your product, have dependencies on c.cover and other add'ons in the metadata.xml and always run the policy update last after the other add'ons have modified the settings. But it's still cumbersome.

**Comment by hvelarde** [comment]
I think @idgserpro still has a point on this; the solution could be very easy implement and will solve some head aches.

**Comment by idgserpro** [comment]
@fredvd 

Even with the default collective.cover styles  being added again, I think better than all styles be removed.

**Comment by hvelarde** [comment]
@idgserpro guys, please help solving this: open a branch and create a pull request with the solution; I have only 2 hands.
