### ISSUE TITLE
Implement drag and drop among tiles

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#487]
We have a requirement from one of our customers to implement this feature, as they spend endless hours editing the front page of their site just to move items among tiles.

Currently we only support to drag and drop content inside a list tile to change the order of an item on it. We need to be able of moving items as well.

As implementing this in all tiles will be very complex, I suggest to start supporting only basic and list tiles (that's probably 80% of the use cases):

* moving an item from a basic tile to another tile: all customized data must be copied; the first tile must be emptied; on a full list the effect must be the same as adding a new item on the list: the last element is gone (we need to check the current behavior)
* moving an item from a list tile to another tile: all customized data must be copied; the item is removed from the list in the first tile

## Risks ##
* We can lose information (i.e. a customized image) on custom fields not supported in the list tile (we need to check this)
* To avoid losing information in case of an error, is better to copy the information in the second tile before erasing it from the first one
* I haven't tested if the functionality included in #451 has some unexpected consequences on the current feature
* We need to update the RF tests and that could be painful

**Comment by rodfersou** [comment]
* Knowing that we have many tiles with totally different custom elements, after we drop the item from one tile to the other we need to have an overlay box asking to review custom data.
* Other idea is to ask if you want to copy or move data between tiles.
* Looking into jquery ui sortable examples, we need to play with connectWith parameter http://jqueryui.com/sortable/#empty-lists .

**Comment by hvelarde** [comment]
from the UI point of view, I think is a bad idea to open an overlay after dropping some item from one tile to another. the expected behavior must be the same as when moving around an item in the list tile from one position to another; @agnogueira, commentson this?

we can't start imagining all corner cases here, let's just implement the feature and we will discover how to enhance it later. as per the custom elements, we just need to copy those that are editable; I think is OK to lose a custom image when moving an item from a basic tile to a list tile, but title and description must be copied.

please update also the user's manual with information about the limitations of the implementation.

**Comment by rodfersou** [comment]
Thinking about tests, I looked into the mockup package way to make JS tests, and search into p.a.widgets if there are any JS tests.

* Mockup uses a custom way to play the tests with makefiles (and I don't like it).
* P.a.widgets don't have JS tests.

I propose to rewrite the current JS from cover with Yeoman (that I already have more than one year of experience), this way we will have a good frontend framework to deal with bower requirements, tests, and nodejs packages.

Another idea I propose is to use Coffeescript instead of Javascript.  I'm sure that this is by far the best way to lower the gap beetween backend logic and frontend logic, taking advantage of the syntax sugar, and way to write OO code we are already comfortable with in Python that Coffeescript brings to Javascript world.

Ofcourse these changes need to be done with care, and gradually, and I'm open to ideas and sugestions.

**Comment by hvelarde** [comment]
open another issue as enhancement proposal describing those things; we don't have time neither resources for that now.

**Comment by agnogueira** [comment]
Some points:
1. Never open an overlay on drop, its not a expected behavior.
2. Yes, move a item from a tile to another tile is the same as move an item from content chooser to a tile. It should use the same validations (you can drop at some tiles, not at other tiles...) and behaviors.

**Comment by rodfersou** [comment]
@hvelarde I undestood that tests for JS were desirable in this ticket, forget about it now :)
@agnogueira thanks for the answer:

1) got it
2) And if there is some customized title or description or whatever.. tiles have different data, and should not lose it when drag and drop from different tiles.

**Comment by hvelarde** [comment]
@rodfersou I think this could be useful: https://jqueryui.com/sortable/#connect-lists
