### ISSUE TITLE
AssertionError: Page should have contained text 'Export layout' but did not

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#582]
We have some RF tests randomly failing with this message; the problem seems to be originated on an issue with the modal used to edit a tile:

![robot_test_file_tile_test_file_tile_selenium-screenshot-1](https://cloud.githubusercontent.com/assets/341393/12447482/930e6dfc-bf57-11e5-847c-208d0ad6f08f.png)

More information here: https://s3-sa-east-1.amazonaws.com/collective-cover/collective/collective.cover/2515/2515.1/parts/test/robot_log.html

**Comment by idgserpro** [comment]
The time frame between the last test that passed and the one that fails is *really* small.

The one that passes:
Start / End / Elapsed:	20160119 18:03:23.018 / 20160119 **18:03:23.033** / 00:00:00.015

The one that fails:
Start / End / Elapsed:	20160119 **18:03:23.034** / 20160119 18:03:24.371 / 00:00:01.337

Some tests with the same difference in time frame passes though, so I don't know if that matters. Do the **same** tests always fails randomly, or, randomly, *different* tests fail?

**Comment by hvelarde** [comment]
we have a test matrix with about 7 builds now; sometimes some of this tests fail in different builds

**Comment by idgserpro** [comment]
So, it's completely random - breakage and tests? Do the tests that fail in all of these builds have the same small time frame like the example in https://github.com/collective/collective.cover/issues/582#issuecomment-173214284?

**Comment by hvelarde** [comment]
I have no idea :-)

**Comment by idgserpro** [comment]
What about

```Wait until page contains```

instead of

```Page should contain```

We had a similar problem in https://github.com/plonegovbr/brasil.gov.tiles/commit/7794323a8833632fa2f0ffaad73a8346af96de4a and the folks from Plone itself as well in https://github.com/plone/Products.CMFPlone/commit/389431262d1aa71a2a3b613e3dd86f824fc3b5dd

If this solves your problem, please add a line to the docs in Plone telling about this difference, specially adding "Page should have contained text 'Export layout' but did not" text since that's what usually people search on the internet.

**Comment by hvelarde** [comment]
no, the problem seems to be before that line; if you look at the screenshot seems `Click Button Cancel` is failing and I don't know why

**Comment by idgserpro** [comment]
We've made a combination of this commit https://github.com/collective/collective.cover/commit/0d4c0ba8ba1f7c61d77e8b766d48a74b388b6269 but changing

    Wait Until Keyword Succeeds  5 sec  1 sec

to

    Wait Until Keyword Succeeds  10 sec  2 sec

and

    Page should contain

to

    Wait until page contains

Customizing collective.cover keyword "Edit Cover Layout". Comments are in brazilian portuguese in https://github.com/plonegovbr/brasil.gov.tiles/blob/0a01c8951fd0ef96ecd3b1b21d4570562dd880a8/src/brasil/gov/tiles/tests/test_albuns_tile.robot#L28 but I think you can get the idea.

Looking at the issue's screenshot, it seems robots can't see the "Layout" link since the modal is still in place (maybe a firefox memory issue when fading it?), and since this is an intermitent problem, we tought about a timing issue - that's what motivated our solution above.

We haven't made a pull request or something like that to collective.cover since we don't know the impacts: our package can handle this overhead, but collective.cover isn't trivial.

**Comment by idgserpro** [comment]
It's still not working. It worked in two builds in a row, now stopped working. We're still in the same boat. :(

This only happens on Travis, though.

**Comment by hvelarde** [comment]
run the tests using the following:

    ROBOT_SELENIUM_RUN_ON_FAILURE=Debug bin/test --layer=Robot

**Comment by hvelarde** [comment]
still failing https://travis-ci.org/collective/collective.cover/jobs/113498588
