### ISSUE TITLE
Implement CSRF protection for Plone 5

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#590]
In 657f1e60e21fb8c3cd79e7fb3bbfa7d9bdf5e947 @alecpm started some work to implement CSRF protection into the package; we need to review it and finish the work.

**Comment by idgserpro** [comment]
@hvelarde  @rodfersou  the authenticator is only necessary in Plone 5. See:

https://github.com/plone/plone.protect/issues/42

In Plone 4 with plone4.csrffixes and Plone 4 without plone4.csrffixes it's not necessary. I [removed the authenticator](https://github.com/collective/collective.cover/commit/fd9499776b651efe6e5db6133ec4c646ebd8ccbf) and the [tests passed](https://travis-ci.org/collective/collective.cover/builds/131156843) with plone4.csrffixes.

As the cc is not working in Plone 5 still do not think it should be fixed now.

I suggest closing the PR #594 and change the title of this issue to be fix in Plone 5. Do you agree?

**Comment by hvelarde** [comment]
I have no opinion on this at this time.

**Comment by idgserpro** [comment]
Guys, any opinion on this matter? Specially about https://github.com/collective/collective.cover/issues/590#issuecomment-220107695

@alecpm @rodfersou @frapell @jpgimenez @djowett @fredvd

**Comment by rodfersou** [comment]
@idgserpro digging into the threads I found what you are talking about.. [protect.js automatically add the token](https://github.com/plone/plone4.csrffixes/blob/f6cebe87896548352551c9462cc0f454c3fbeb66/plone4/csrffixes/protect.js#L26) for ajax calls.

But my question is.. what is the difference beetween the ``X-CSRF-TOKEN`` header and the ``_authenticator`` parameter that [we add in this pull request](https://github.com/collective/collective.cover/pull/594/files)?

I think we should wait for the decicion of [this issue](https://github.com/plone/plone.protect/issues/42) before continue with this work.

About your experiment removing the authentication and keeping the tests that didn't fail, that's interesting, it should fail..

**Comment by djowett** [comment]
Sorry, no time to form an opinion on this one. Glad you guys are working on it. 

Sent from my Sony Xperia™ smartphone

---- Rodrigo Ferreira de Souza wrote ----

**Comment by idgserpro** [comment]
> But my question is.. what is the difference beetween the X-CSRF-TOKEN header and the _authenticator parameter that we add in this pull request?

@rodfersou From an end user perspective, none. You can see [in this commit](https://github.com/plone/plone.protect/blob/0d53d79dd3cd158c22689746a181199678765668/plone/protect/authenticator.py#L63) that if `_authenticator` is not found, it checks for `X-CSRF-TOKEN` to add csrf protection.

From an implementation perspective, this means less code and being less error prone, since all AJAX calls will have the token in the request instead of manually adding it to your javascript. The way it's done now, if you add another call to your javascript you need to remember to add, again, `_authenticator` to your request.

The experiment don't fail in Plone 4.3 because of plone4.csrffixes, this package adds the `X-CRSF-TOKEN` in all requests.

**Comment by idgserpro** [comment]
See too: https://github.com/plone/plone.protect#headers

**Comment by hvelarde** [comment]
so we can add the authenticator based on the Plone version used, right? we can leave this pending until we can make more advances on Plone 5 compatibility.

**Comment by idgserpro** [comment]
@hvelarde right. I change the title of this issue to make this clearer.

**Comment by idgserpro** [comment]
protect.js was added in plone.protect:

https://github.com/plone/plone.protect/pull/49
